package koporscho;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Koporscho csapat Projlab 
//  @ File Name : IVis.java
//  @ Date : 2022. 03. 25.
//  @ Authors : Szabó Egon, Biró Ferenc, Tóth Bólint, Ferge Mótó, Rahmi Dóniel
//
//




/** Visitor interface. Mezőkkel való interakciókért felelős */
public interface IVis {
	/** A várossal való interakciókért felelős. */
    void InteractCity();

	/** Az óvóhellyel való interakciókért felelős.*/
    void InteractShelter();
	
	/** A raktárral való interakciókért felelős.*/
    void InteractStorage();
	
	/** A laboratóriummal való interakciókért felelős.*/
    void InteractLab();
}
